### ISSUE TITLE
Recursion limit reached when operating on multidimensional MeasurementArrays

### ISSUE THREAD

**Issue by gristim** [Queens-Physics/qexpy#56]
The following code behaves as expected:
```
>>> import qexpy as q
>>> import numpy as np
>>> rng = np.random.default_rng()
>>> a = rng.standard_normal(1000)
>>> b = np.abs(rng.standard_normal(1000))
>>> c = q.MeasurementArray(a, b)
>>> c.mean()
MeasuredValue(-0.01 +/- 0.03)
```

However, if you were to convert the MeasurementArray object into a `np.ndarray` using the `np.asarray()` function, you would get a `RecursionError`:
```
import qexpy as q
>>> import numpy as np
>>> rng = np.random.default_rng()
>>> a = rng.standard_normal(1000)
>>> b = np.abs(rng.standard_normal(1000))
>>> c = q.MeasurementArray(a, b)
>>> d = np.asarray(c)
>>> d.mean()
Traceback (most recent call last):
  File "/home/timkhoo/.local/lib/python3.10/site-packages/qexpy/data/operations.py", line 432, in _evaluate_formula
    return OPERATIONS[formula.operator](*operands)
  File "/home/timkhoo/.local/lib/python3.10/site-packages/qexpy/data/operations.py", line 431, in <genexpr>
    operands = (_evaluate_formula(variable, samples) for variable in formula.operands)
  File "/home/timkhoo/.local/lib/python3.10/site-packages/qexpy/data/operations.py", line 427, in _evaluate_formula
    return _evaluate_formula(formula._formula, samples)
  File "/home/timkhoo/.local/lib/python3.10/site-packages/qexpy/data/operations.py", line 426, in _evaluate_formula
    if isinstance(formula, dt.DerivedValue):
  ...
  File "/home/timkhoo/.local/lib/python3.10/site-packages/qexpy/data/operations.py", line 432, in _evaluate_formula
    return OPERATIONS[formula.operator](*operands)
  File "/home/timkhoo/.local/lib/python3.10/site-packages/qexpy/data/operations.py", line 431, in <genexpr>
    operands = (_evaluate_formula(variable, samples) for variable in formula.operands)
  File "/home/timkhoo/.local/lib/python3.10/site-packages/qexpy/data/operations.py", line 427, in _evaluate_formula
    return _evaluate_formula(formula._formula, samples)
  File "/home/timkhoo/.local/lib/python3.10/site-packages/qexpy/data/operations.py", line 426, in _evaluate_formula
    if isinstance(formula, dt.DerivedValue):
  File "/usr/lib64/python3.10/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```
The need to convert from an ExperimentalValueArray into an ndarray stems from a need to process multidimensional arrays, i.e. `d.reshape(10, 10, 10)`. Multidimensional MeasurementArrays are necessary when attempting to create 2D heatmaps, like in `matplotlib.pyplot.pcolormesh` plots. This can be fixed by overriding the default recursion limit in python:
```
>>>import qexpy as q
>>>sys.setrecursionlimit(1e6)
```
This could serve as a temporary solution until multidimensional arrays are fully implemented. Though perhaps there should be some form of warning that allows the user to make that choice themselves.

**Comment by astralcai** [comment]
Hi, can you provide more information on this problem? I don't think the MeasurementArray right now is designed for multidimensional arrays, so bugs could be expected. You're welcome to fix it by opening up a pull request. I'm currently working on a partial refactor to clean up the code, so this could be included in the next version. Can you elaborate on the actual use case of a multidimensional measurement array?

**Comment by gristim** [comment]
> Hi, can you provide more information on this problem? I don't think the MeasurementArray right now is designed for multidimensional arrays, so bugs could be expected. You're welcome to fix it by opening up a pull request. I'm currently working on a partial refactor to clean up the code, so this could be included in the next version. Can you elaborate on the actual use case of a multidimensional measurement array?

I have updated the issue with more information.
